import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import CustomHeader from '@/components/header'
import PersonFooter from '@/components/personFooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className='flex flex-col items-center'>
      <CustomHeader />
        {children}
      <PersonFooter/>
        </body>
    </html>
  )
}